[pgagroal-coordinator]
host = 0.0.0.0
port = 6432
management = 6433
user = admin

log_type = console
log_level = info
log_path =

ev_backend = auto

[node1]
host = 10.0.0.11
management = 2346

[node2]
host = 10.0.0.12
management = 2346
